# Generated by Django 4.2 on 2023-05-16 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.URLField()),
                ('splashart', models.URLField()),
                ('skin_splashart', models.URLField()),
                ('card', models.URLField()),
                ('skin_card', models.URLField()),
            ],
        ),
    ]
