characters = [
    {       "name": "Aatrox",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Aatrox.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Aatrox_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Aatrox_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Aatrox_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Aatrox_1.jpg",
    },
    {       "name": "Ahri",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Ahri.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ahri_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ahri_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ahri_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ahri_1.jpg",
    },
    {       "name": "Akali",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Akali.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Akali_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Akali_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Akali_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Akali_1.jpg",
    },
    {       "name": "Akshan",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Akshan.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Akshan_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Akshan_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Akshan_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Akshan_1.jpg",
    },
    {       "name": "Alistar",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Alistar.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Alistar_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Alistar_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Alistar_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Alistar_1.jpg",
    },
    {       "name": "Amumu",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Amumu.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Amumu_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Amumu_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Amumu_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Amumu_1.jpg",
    },
    {       "name": "Anivia",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Anivia.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Anivia_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Anivia_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Anivia_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Anivia_1.jpg",
    },
    {       "name": "Annie",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Annie.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Annie_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Annie_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Annie_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Annie_1.jpg",
    },
    {       "name": "Aphelios",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Aphelios.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Aphelios_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Aphelios_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Aphelios_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Aphelios_1.jpg",
    },
    {       "name": "Ashe",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Ashe.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ashe_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ashe_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ashe_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ashe_1.jpg",
    },
    {        "name": "Aurelion Sol",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/AurelionSol.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/AurelionSol_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/AurelionSol_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/AurelionSol_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/AurelionSol_1.jpg",
    },
    {        "name": "Azir",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Azir.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Azir_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Azir_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Azir_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Azir_1.jpg",
    },
    {        "name": "Bardo",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Bard.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Bard_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Bard_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Bard_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Bard_1.jpg",
    },
    {        "name": "Bel'Veth",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Belveth.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Belveth_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Belveth_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Belveth_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Belveth_1.jpg",
    },
    {        "name": "Blitzcrank",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Blitzcrank.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Blitzcrank_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Blitzcrank_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Blitzcrank_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Blitzcrank_1.jpg",
    },
    {        "name": "Brand",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Brand.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Brand_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Brand_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Brand_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Brand_1.jpg",
    },
    {        "name": "Braum",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Braum.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Braum_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Braum_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Braum_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Braum_1.jpg",
    },
    {        "name": "Caitlyn",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Caitlyn.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Caitlyn_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Caitlyn_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Caitlyn_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Caitlyn_1.jpg",
    },
    {        "name": "Camille",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Camille.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Camille_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Camille_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Camille_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Camille_1.jpg",
    },
    {        "name": "Cassiopeia",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Cassiopeia.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Cassiopeia_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Cassiopeia_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Cassiopeia_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Cassiopeia_1.jpg",
    },
    {        "name": "Cho'Gath",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Chogath.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Chogath_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Chogath_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Chogath_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Chogath_1.jpg",
    },
    {        "name": "Corki",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Corki.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Corki_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Corki_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Corki_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Corki_1.jpg",
    },
    {        "name": "Darius",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Darius.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Darius_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Darius_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Darius_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Darius_1.jpg",
    },
    {        "name": "Diana",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Diana.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Diana_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Diana_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Diana_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Diana_1.jpg",
    },
    {        "name": "Draven",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Draven.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Draven_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Draven_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Draven_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Draven_1.jpg",
    },
    {        "name": "Dr. Mundo",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/DrMundo.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/DrMundo_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/DrMundo_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/DrMundo_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/DrMundo_1.jpg",
    },
    {        "name": "Ekko",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Ekko.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ekko_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ekko_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ekko_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ekko_1.jpg",
    },
    {        "name": "Elise",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Elise.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Elise_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Elise_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Elise_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Elise_1.jpg",
    },
    {        "name": "Evelynn",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Evelynn.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Evelynn_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Evelynn_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Evelynn_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Evelynn_1.jpg",
    },
    {        "name": "Ezreal",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Ezreal.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ezreal_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ezreal_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ezreal_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ezreal_1.jpg",
    },
    {        "name": "Fiddlesticks",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Fiddlesticks.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Fiddlesticks_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Fiddlesticks_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Fiddlesticks_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Fiddlesticks_1.jpg",
    },
    {        "name": "Fiora",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Fiora.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Fiora_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Fiora_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Fiora_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Fiora_1.jpg",
    },
    {        "name": "Fizz",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Fizz.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Fizz_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Fizz_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Fizz_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Fizz_1.jpg",
    },
    {        "name": "Galio",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Galio.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Galio_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Galio_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Galio_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Galio_1.jpg",
    },
    {        "name": "Gangplank",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Gangplank.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Gangplank_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Gangplank_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Gangplank_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Gangplank_1.jpg",
    },
    {        "name": "Garen",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Garen.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Garen_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Garen_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Garen_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Garen_1.jpg",
    },
    {        "name": "Gnar",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Gnar.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Gnar_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Gnar_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Gnar_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Gnar_1.jpg",
    },
    {        "name": "Gragas",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Gragas.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Gragas_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Gragas_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Gragas_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Gragas_1.jpg",
    },
    {        "name": "Graves",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Graves.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Graves_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Graves_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Graves_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Graves_1.jpg",
    },
    {        "name": "Gwen",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Gwen.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Gwen_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Gwen_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Gwen_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Gwen_1.jpg",
    },
    {        "name": "Hecarim",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Hecarim.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Hecarim_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Hecarim_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Hecarim_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Hecarim_1.jpg",
    },
    {        "name": "Heimerdinger",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Heimerdinger.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Heimerdinger_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Heimerdinger_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Heimerdinger_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Heimerdinger_1.jpg",
    },
    {        "name": "Illaoi",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Illaoi.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Illaoi_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Illaoi_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Illaoi_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Illaoi_1.jpg",
    },
    {        "name": "Irelia",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Irelia.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Irelia_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Irelia_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Irelia_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Irelia_1.jpg",
    },
    {        "name": "Ivern",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Ivern.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ivern_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ivern_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ivern_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ivern_1.jpg",
    },
    {        "name": "Janna",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Janna.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Janna_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Janna_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Janna_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Janna_1.jpg",
    },
    {        "name": "Jarvan IV",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/JarvanIV.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/JarvanIV_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/JarvanIV_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/JarvanIV_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/JarvanIV_1.jpg",
    },
    {        "name": "Jax",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Jax.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Jax_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Jax_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Jax_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Jax_1.jpg",
    },
    {        "name": "Jayce",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Jayce.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Jayce_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Jayce_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Jayce_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Jayce_1.jpg",
    },
    {        "name": "Jhin",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Jhin.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Jhin_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Jhin_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Jhin_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Jhin_1.jpg",
    },
    {        "name": "Jinx",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Jinx.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Jinx_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Jinx_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Jinx_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Jinx_1.jpg",
    },
    {        "name": "Kai'Sa",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Kaisa.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kaisa_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kaisa_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Kaisa_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Kaisa_1.jpg",
    },
    {        "name": "Kalista",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Kalista.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kalista_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kalista_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Kalista_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Kalista_1.jpg",
    },
    {        "name": "Karma",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Karma.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Karma_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Karma_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Karma_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Karma_1.jpg",
    },
    {        "name": "Karthus",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Karthus.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Karthus_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Karthus_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Karthus_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Karthus_1.jpg",
    },
    {        "name": "Kassadin",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Kassadin.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kassadin_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kassadin_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Kassadin_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Kassadin_1.jpg",
    },
    {        "name": "Katarina",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Katarina.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Katarina_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Katarina_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Katarina_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Katarina_1.jpg",
    },
    {        "name": "Kayle",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Kayle.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kayle_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kayle_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Kayle_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Kayle_1.jpg",
    },
    {        "name": "Kayn",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Kayn.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kayn_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kayn_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Kayn_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Kayn_1.jpg",
    },
    {        "name": "Kennen",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Kennen.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kennen_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kennen_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Kennen_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Kennen_1.jpg",
    },
    {        "name": "Kha'Zix",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Khazix.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Khazix_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Khazix_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Khazix_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Khazix_1.jpg",
    },
    {        "name": "Kindred",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Kindred.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kindred_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kindred_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Kindred_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Kindred_1.jpg",
    },
    {        "name": "Kled",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Kled.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kled_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kled_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Kled_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Kled_1.jpg",
    },
    {        "name": "Kog'Maw",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/KogMaw.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/KogMaw_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/KogMaw_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/KogMaw_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/KogMaw_1.jpg",
    },
    {        "name": "LeBlanc",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Leblanc.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Leblanc_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Leblanc_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Leblanc_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Leblanc_1.jpg",
    },
    {        "name": "Lee Sin",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/LeeSin.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/LeeSin_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/LeeSin_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/LeeSin_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/LeeSin_1.jpg",
    },
    {        "name": "Leona",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Leona.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Leona_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Leona_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Leona_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Leona_1.jpg",
    },
    {        "name": "Lillia",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Lillia.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Lillia_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Lillia_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Lillia_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Lillia_1.jpg",
    },
    {        "name": "Lissandra",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Lissandra.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Lissandra_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Lissandra_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Lissandra_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Lissandra_1.jpg",
    },
    {        "name": "Lucian",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Lucian.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Lucian_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Lucian_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Lucian_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Lucian_1.jpg",
    },
    {        "name": "Lulu",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Lulu.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Lulu_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Lulu_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Lulu_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Lulu_1.jpg",
    },
    {        "name": "Lux",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Lux.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Lux_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Lux_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Lux_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Lux_1.jpg",
    },
    {        "name": "Malphite",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Malphite.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Malphite_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Malphite_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Malphite_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Malphite_1.jpg",
    },
    {        "name": "Malzahar",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Malzahar.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Malzahar_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Malzahar_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Malzahar_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Malzahar_1.jpg",
    },
    {        "name": "Maokai",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Maokai.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Maokai_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Maokai_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Maokai_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Maokai_1.jpg",
    },
    {        "name": "Master Yi",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/MasterYi.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/MasterYi_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/MasterYi_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/MasterYi_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/MasterYi_1.jpg",
    },
    {        "name": "Miss Fortune",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/MissFortune.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/MissFortune_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/MissFortune_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/MissFortune_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/MissFortune_1.jpg",
    },
    {        "name": "Wukong",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/MonkeyKing.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/MonkeyKing_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/MonkeyKing_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/MonkeyKing_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/MonkeyKing_1.jpg",
    },
    {        "name": "Mordekaiser",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Mordekaiser.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Mordekaiser_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Mordekaiser_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Mordekaiser_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Mordekaiser_1.jpg",
    },
    {        "name": "Morgana",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Morgana.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Morgana_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Morgana_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Morgana_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Morgana_1.jpg",
    },
    {        "name": "Nami",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Nami.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Nami_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Nami_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Nami_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Nami_1.jpg",
    },
    {        "name": "Nasus",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Nasus.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Nasus_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Nasus_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Nasus_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Nasus_1.jpg",
    },
    {        "name": "Nautilus",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Nautilus.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Nautilus_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Nautilus_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Nautilus_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Nautilus_1.jpg",
    },
    {        "name": "Neeko",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Neeko.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Neeko_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Neeko_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Neeko_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Neeko_1.jpg",
    },
    {        "name": "Nidalee",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Nidalee.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Nidalee_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Nidalee_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Nidalee_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Nidalee_1.jpg",
    },
    {        "name": "Nilah",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Nilah.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Nilah_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Nilah_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Nilah_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Nilah_1.jpg",
    },
    {        "name": "Nocturne",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Nocturne.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Nocturne_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Nocturne_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Nocturne_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Nocturne_1.jpg",
    },
    {        "name": "Nunu e Willump",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Nunu.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Nunu_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Nunu_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Nunu_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Nunu_1.jpg",
    },
    {        "name": "Olaf",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Olaf.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Olaf_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Olaf_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Olaf_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Olaf_1.jpg",
    },
    {        "name": "Orianna",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Orianna.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Orianna_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Orianna_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Orianna_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Orianna_1.jpg",
    },
    {        "name": "Ornn",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Ornn.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ornn_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ornn_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ornn_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ornn_1.jpg",
    },
    {        "name": "Pantheon",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Pantheon.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Pantheon_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Pantheon_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Pantheon_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Pantheon_1.jpg",
    },
    {        "name": "Poppy",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Poppy.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Poppy_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Poppy_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Poppy_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Poppy_1.jpg",
    },
    {        "name": "Pyke",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Pyke.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Pyke_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Pyke_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Pyke_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Pyke_1.jpg",
    },
    {        "name": "Qiyana",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Qiyana.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Qiyana_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Qiyana_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Qiyana_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Qiyana_1.jpg",
    },
    {        "name": "Quinn",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Quinn.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Quinn_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Quinn_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Quinn_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Quinn_1.jpg",
    },
    {        "name": "Rakan",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Rakan.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Rakan_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Rakan_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Rakan_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Rakan_1.jpg",
    },
    {        "name": "Rammus",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Rammus.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Rammus_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Rammus_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Rammus_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Rammus_1.jpg",
    },
    {        "name": "Rek'Sai",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/RekSai.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/RekSai_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/RekSai_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/RekSai_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/RekSai_1.jpg",
    },
    {        "name": "Rell",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Rell.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Rell_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Rell_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Rell_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Rell_1.jpg",
    },
    {
        "name": "Renata Glasc",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Renata.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Renata_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Renata_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Renata_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Renata_1.jpg",
    },
    {
        "name": "Renekton",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Renekton.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Renekton_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Renekton_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Renekton_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Renekton_1.jpg",
    },
    {
        "name": "Rengar",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Rengar.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Rengar_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Rengar_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Rengar_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Rengar_1.jpg",
    },
    {
        "name": "Riven",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Riven.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Riven_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Riven_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Riven_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Riven_1.jpg",
    },
    {
        "name": "Rumble",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Rumble.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Rumble_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Rumble_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Rumble_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Rumble_1.jpg",
    },
    {
        "name": "Ryze",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Ryze.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ryze_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ryze_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ryze_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ryze_1.jpg",
    },
    {
        "name": "Samira",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Samira.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Samira_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Samira_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Samira_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Samira_1.jpg",
    },
    {
        "name": "Sejuani",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Sejuani.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sejuani_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sejuani_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Sejuani_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Sejuani_1.jpg",
    },
    {
        "name": "Senna",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Senna.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Senna_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Senna_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Senna_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Senna_1.jpg",
    },
    {
        "name": "Seraphine",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Seraphine.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Seraphine_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Seraphine_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Seraphine_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Seraphine_1.jpg",
    },
    {
        "name": "Sett",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Sett.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sett_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sett_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Sett_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Sett_1.jpg",
    },
    {
        "name": "Shaco",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Shaco.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Shaco_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Shaco_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Shaco_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Shaco_1.jpg",
    },
    {
        "name": "Shen",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Shen.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Shen_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Shen_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Shen_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Shen_1.jpg",
    },
    {
        "name": "Shyvana",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Shyvana.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Shyvana_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Shyvana_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Shyvana_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Shyvana_1.jpg",
    },
    {
        "name": "Singed",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Singed.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Singed_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Singed_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Singed_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Singed_1.jpg",
    },
    {
        "name": "Sion",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Sion.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sion_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sion_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Sion_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Sion_1.jpg",
    },
    {
        "name": "Sivir",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Sivir.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sivir_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sivir_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Sivir_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Sivir_1.jpg",
    },
    {
        "name": "Skarner",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Skarner.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Skarner_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Skarner_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Skarner_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Skarner_1.jpg",
    },
    {
        "name": "Sona",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Sona.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sona_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sona_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Sona_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Sona_1.jpg",
    },
    {
        "name": "Soraka",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Soraka.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Soraka_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Soraka_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Soraka_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Soraka_1.jpg",
    },
    {
        "name": "Swain",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Swain.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Swain_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Swain_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Swain_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Swain_1.jpg",
    },
    {
        "name": "Sylas",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Sylas.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sylas_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sylas_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Sylas_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Sylas_1.jpg",
    },
    {
        "name": "Syndra",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Syndra.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Syndra_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Syndra_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Syndra_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Syndra_1.jpg",
    },
    {
        "name": "Tahm Kench",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/TahmKench.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/TahmKench_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/TahmKench_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/TahmKench_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/TahmKench_1.jpg",
    },
    {
        "name": "Taliyah",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Taliyah.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Taliyah_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Taliyah_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Taliyah_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Taliyah_1.jpg",
    },
    {
        "name": "Talon",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Talon.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Talon_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Talon_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Talon_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Talon_1.jpg",
    },
    {
        "name": "Taric",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Taric.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Taric_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Taric_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Taric_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Taric_1.jpg",
    },
    {
        "name": "Teemo",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Teemo.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Teemo_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Teemo_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Teemo_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Teemo_1.jpg",
    },
    {
        "name": "Thresh",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Thresh.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Thresh_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Thresh_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Thresh_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Thresh_1.jpg",
    },
    {
        "name": "Tristana",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Tristana.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Tristana_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Tristana_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Tristana_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Tristana_1.jpg",
    },
    {
        "name": "Trundle",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Trundle.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Trundle_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Trundle_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Trundle_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Trundle_1.jpg",
    },
    {
        "name": "Tryndamere",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Tryndamere.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Tryndamere_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Tryndamere_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Tryndamere_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Tryndamere_1.jpg",
    },
    {
        "name": "Twisted Fate",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/TwistedFate.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/TwistedFate_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/TwistedFate_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/TwistedFate_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/TwistedFate_1.jpg",
    },
    {
        "name": "Twitch",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Twitch.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Twitch_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Twitch_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Twitch_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Twitch_1.jpg",
    },
    {
        "name": "Udyr",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Udyr.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Udyr_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Udyr_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Udyr_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Udyr_1.jpg",
    },
    {
        "name": "Urgot",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Urgot.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Urgot_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Urgot_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Urgot_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Urgot_1.jpg",
    },
    {
        "name": "Varus",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Varus.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Varus_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Varus_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Varus_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Varus_1.jpg",
    },
    {
        "name": "Vayne",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Vayne.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Vayne_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Vayne_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Vayne_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Vayne_1.jpg",
    },
    {
        "name": "Veigar",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Veigar.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Veigar_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Veigar_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Veigar_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Veigar_1.jpg",
    },
    {
        "name": "Vel'Koz",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Velkoz.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Velkoz_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Velkoz_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Velkoz_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Velkoz_1.jpg",
    },
    {
        "name": "Vex",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Vex.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Vex_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Vex_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Vex_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Vex_1.jpg",
    },
    {
        "name": "Vi",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Vi.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Vi_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Vi_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Vi_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Vi_1.jpg",
    },
    {
        "name": "Viego",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Viego.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Viego_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Viego_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Viego_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Viego_1.jpg",
    },
    {
        "name": "Viktor",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Viktor.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Viktor_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Viktor_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Viktor_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Viktor_1.jpg",
    },
    {
        "name": "Vladimir",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Vladimir.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Vladimir_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Vladimir_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Vladimir_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Vladimir_1.jpg",
    },
    {
        "name": "Volibear",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Volibear.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Volibear_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Volibear_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Volibear_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Volibear_1.jpg",
    },
    {
        "name": "Warwick",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Warwick.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Warwick_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Warwick_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Warwick_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Warwick_1.jpg",
    },
    {
        "name": "Xayah",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Xayah.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Xayah_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Xayah_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Xayah_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Xayah_1.jpg",
    },
    {
        "name": "Xerath",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Xerath.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Xerath_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Xerath_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Xerath_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Xerath_1.jpg",
    },
    {
        "name": "Xin Zhao",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/XinZhao.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/XinZhao_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/XinZhao_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/XinZhao_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/XinZhao_1.jpg",
    },
    {
        "name": "Yasuo",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Yasuo.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Yasuo_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Yasuo_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Yasuo_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Yasuo_1.jpg",
    },
    {
        "name": "Yone",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Yone.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Yone_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Yone_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Yone_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Yone_1.jpg",
    },
    {
        "name": "Yorick",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Yorick.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Yorick_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Yorick_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Yorick_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Yorick_1.jpg",
    },
    {
        "name": "Yuumi",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Yuumi.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Yuumi_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Yuumi_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Yuumi_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Yuumi_1.jpg",
    },
    {
        "name": "Zac",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Zac.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zac_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zac_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Zac_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Zac_1.jpg",
    },
    {
        "name": "Zed",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Zed.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zed_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zed_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Zed_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Zed_1.jpg",
    },
    {
        "name": "Zeri",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Zeri.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zeri_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zeri_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Zeri_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Zeri_1.jpg",
    },
    {
        "name": "Ziggs",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Ziggs.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ziggs_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ziggs_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ziggs_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ziggs_1.jpg",
    },
    {
        "name": "Zilean",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Zilean.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zilean_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zilean_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Zilean_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Zilean_1.jpg",
    },
    {
        "name": "Zoe",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Zoe.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zoe_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zoe_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Zoe_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Zoe_1.jpg",
    },
    {
        "name": "Zyra",
        "icon": "https://ddragon.leagueoflegends.com/cdn/12.23.1/img/champion/Zyra.png",
        "splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zyra_0.jpg",
        "skin_splashart": "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zyra_1.jpg",
        "card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Zyra_0.jpg",
        "skin_card": "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Zyra_1.jpg",
    },
]
